# Clippy configuration for Web3 Wallet CLI
# Enforces constitutional security and quality requirements

# Performance and efficiency
avoid-breaking-exported-api = true
msrv = "1.70"

# Security-focused lints (constitutional requirement: security-first)
# These align with cryptographic application security standards

# Cognitive complexity limits
cognitive-complexity-threshold = 30
type-complexity-threshold = 250

# Documentation requirements
missing-docs-in-crate-items = false
doc-valid-idents = [
    "BIP39", "BIP44", "HD", "MetaMask", "AES", "GCM", "PBKDF2", "Argon2",
    "JSON", "CLI", "API", "OS", "URL", "URI", "UUID", "UTF8", "ASCII",
    "Ethereum", "ETH", "Web3", "DApp", "RPC", "HTTP", "HTTPS"
]

# String and literal limits
literal-representation-threshold = 1000

# Function complexity
too-many-arguments-threshold = 7
too-many-lines-threshold = 100

# Enum variant name threshold
enum-variant-name-threshold = 3

# Vector and collection limits
vec-box-size-threshold = 4096
pass-by-value-size-limit = 256

# Performance thresholds
trivial-copy-size-limit = 128

# Security-relevant settings
allow-expect-in-tests = true
allow-unwrap-in-tests = true

# Disable lints that may conflict with security patterns
# (We want explicit error handling as per constitution)
disallowed-methods = [
    "std::env::var",  # Use structured configuration instead
    "std::process::exit",  # Use proper error propagation
]

# Allow certain patterns needed for crypto operations
single-char-binding-names-threshold = 4