# Rust formatting configuration for Web3 Wallet CLI
# Follows constitutional requirements for code quality and consistency

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import organization
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Function and control flow formatting
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_code_in_doc_comments = true

# Struct and enum formatting
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# String formatting
format_strings = true
format_macro_matchers = true

# Comment formatting
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80

# Error handling (align with constitutional requirements)
use_try_shorthand = true
force_explicit_abi = true

# Security and safety related
unsafe_block_in_unsafe_fn = "Allow"

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Miscellaneous
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true

# Newline and whitespace
newline_style = "Unix"
indent_style = "Block"
match_block_trailing_comma = true